apiVersion: v1
kind: PersistentVolume
metadata:
  name: fileserver-httpd
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  #Criar nfs in server
  nfs:
    path: /dados
    server: 10.111.75.10

---
#Claim de acesso ao PV
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fileserver-httpd
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: fileserver-httpd
  resources:
    requests:
      storage: 5Gi

---
#Deployment da aplicação
apiVersion: v1
kind: Deployment
metadata:
  name: httpd
spec:
  replicas: 6
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - image: httpd:latest
        name: httpd
        ports:
        - containerPort: 80
          name: httpd

        volumeMounts:
        - name: fileserver-httpd
          mountPath: /usr/local/apache2/htdocs/
      volumes:
      - name: fileserver-httpd
        persistentVolumeClaim:
          claimName: fileserver-httpd