apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: Senha123
        - name: MYSQL_DATABASE
          value: meubanco
        ports:
        - containerPort: 3306
          name: mysql
        # Volume montado dentro da estrutura do cluster
       # volumeMounts:
       # - name: local
       #   mountPath: /var/lib/mysql
      # Volume montado local - máquina - storage...   
      # Inserido dentro do Nó - Cluster 
      volumes:
      - name: myclaim
        #persistentVolumeClaim:
        #  claimName: myclaim
        #hostPath:
        #path: /meubanco/
        nfs:
          path: /Houer Ti - Suporte
          server: 192.168.0.36