apiVersion: v1
kind: PersistentVolume
metadata:
  name: myclaim
  labels:
    type: myclaim
spec:
  # Se fosse usar ntfs - no lugar de manual
  #storageClassName: manual
  capacity:
    storage: 50Mi
  volumeMode: Filesystem
  accessModes:
  # ReadOnlyMany - volume somente leitura por muitos nós
  # ReadWriteMany - volume como rw por muitos nós
  # RWM - Compute Engine não é compatível com esse modo
  # volume pode ser montado como rw por um unico nó
    - ReadWriteOnce
  #Deprecated - Recycle, Delete, Retain
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /Houer Ti - Suporte
    server: 192.168.0.36

  #hostPath:
  #  path: /meubanco/
    
