apiVersion: v1
# O PVC e a requisição de uso - requisita um pv
kind: PersistentVolumeClaim
metadata:
  #name: local
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Mi
  storageClassName: slow
  #selector:
  #  matchLabels:
  #  release: "stable"
  
  
  